export interface Medspa {
  id: string;
  medspa_name: string;
  village: string;
  location: string;
  address?: string;
  number?: string;
  google_star?: number;
  google_review?: number;
  yelp_star?: number;
  yelp_review?: number;
  best_treatment?: string;
  best_treatment1?: string;
  best_treatment2?: string;
  best_treatment3?: string;
  free_consultation?: string;
  good_review_short?: string;
  bad_review_short?: string;
  good_review_deepdive1?: string;
  good_review_deepdive1_explanation?: string;
  good_review_deepdive2?: string;
  good_review_deepdive2_explanation?: string;
  good_review_deepdive3?: string;
  good_review_deepdive3_explanation?: string;
  bad_review_deepdive1?: string;
  bad_review_deepdive1_explanation?: string;
  bad_review_deepdive2?: string;
  bad_review_deepdive2_explanation?: string;
  bad_review_deepdive3?: string;
  bad_review_deepdive3_explanation?: string;
  recommended_practitioner1_name?: string;
  recommended_practitioner1_reason?: string;
  recommended_practitioner2_name?: string;
  recommended_practitioner2_reason?: string;
  recommended_practitioner3_name?: string;
  recommended_practitioner3_reason?: string;
  treatment1?: string;
  price1?: string;
  treatment2?: string;
  price2?: string;
  treatment3?: string;
  price3?: string;
  treatment4?: string;
  price4?: string;
  treatment5?: string;
  price5?: string;
  treatment6?: string;
  price6?: string;
  image_url1: string;
  image_url2?: string; 
  image_url3?: string;
  lat?: number;
  lng?: number;
  coordinates?: {
    lat: number;
    lng: number;
  };
  review1_text?: string;
  review1_author?: string;
  review1_author_photo?: string;
  review1_date?: string;
  review1_rating?: number;
  review2_text?: string;
  review2_author?: string;
  review2_author_photo?: string;
  review2_date?: string;
  review2_rating?: number;
  review3_text?: string;
  review3_author?: string;
  review3_author_photo?: string;
  review3_date?: string;
  review3_rating?: number;
  review4_text?: string;
  review4_author?: string;
  review4_author_photo?: string;
  review4_date?: string;
  review4_rating?: number;
  review5_text?: string;
  review5_author?: string;
  review5_author_photo?: string;
  review5_date?: string;
  review5_rating?: number;
  google_map_link?: string;
  yelp_url?: string;
  instagram?: string;
  website?: string;
}

export interface PriceData {
  id: string;
  medspa_id: string;
  medspa_name?: string;
  treatment_category?: string;
  efficacy?: string;
  treatment_name?: string;
  treatment_description?: string;
  standard_price?: string;
  standard_unit?: string;
  standard_price_note?: string;
  duration?: string;
  member_price?: string;
  member_unit?: string;
  member_price_note?: string;
  package_duration?: string;
  additional_info?: string;
  contact?: string;
}

export interface FilterState {
  priceRange: [number, number];
  googleStars: number[];
  yelpStars: number[];
  villages: string[];
  facilities: string[];
  distance: number | null;
  treatmentCategories: string[];
  efficacies: string[];
  googleReviews: number | null;
  yelpReviews: number | null;
  freeConsultation: boolean | null;
}
